var category = {
    value:"CALORIES", 
    title:"Calories : liste longue.", 
    style:""
};

AppConversions.AddCategory(category.value, category.title, category.style);

var conversions = [
    ["Calorie","1", ""],
["banane","89", "font-weight: bold; color: limegreen;"],
["minute de sexe (hommes)","4.2", ""],
["minute de sexe  (femmes)","3.1", ""],
["verre de Margarita","13.139", ""],
["heure de fonctionnement du cerveau","13.4", ""],
["pain au chocolat","300", ""],

]

AppConversions.AddGroup(category.value, "Unités essentielles", "", conversions);

var conversions = [
    ["	heure de Marche lente 1 heure (3km/h)	","	176	", ""],
["	heure de Marche modérée 1 heure (5km/h)	","	232	", ""],
["	heure de Marche rapide 1 heure (6 à 7 km/h)	","	267	", ""],
["	heure de Marche très rapide 1 heure (8km/h)	","	563	", ""],
["	heure de Marche rapide en montée 1 heure (6km/h)	","	422	", ""],
["	heure de Randonnée (montagne)","	493	", ""],
["	heure de Course à pied lente (9 à 10km/h)","	704	", ""],
["	heure de Course à pied modérée (12 à 13 km/h)","	950	", ""],
["	heure de Course à pied rapide (15 km/h)","	1056	", ""],
["	heure de Vélo vitesse lente (< à 20 km/h)","	422	", ""],
["	heure de Vélo vitesse modérée (20 à 25 km/h)","	563	", ""],
["	heure de Vélo vitesse rapide (Plus de 25km/h)","	844	", ""],
["	heure de Vélo elliptique","	648	", ""],
["	heure de Musculation en circuit training ","	563	", ""],
["	heure de Musculation	 1 heure","	422	", ""],
["	heure de fitness","	598	", ""],
["	heure de Rameur faible intensité","	246	", ""],
["	heure de Rameur intensité modérée","	493	", ""],
["	heure de Rameur intensité élevée","	598	", ""],
["	heure de Aquagym","	281	", ""],
["	heure de Corde à sauter","	704	", ""],
["	heure de Boxe","	844	", ""],
["	heure de Golf","	317	", ""],
["	heure de Escalade","	563	", ""],
["	heure de Natation vitesse lente","	493	", ""],
["	heure de Natation vitesse rapide","	704	", ""],
["	heure de Tennis","	493	", ""],
["	heure de Yoga","	176	", ""],
["	heure de Tai Chi","	281	", ""],
["	heure de Ménage","	246	", ""],
["	heure de Bricolage","	246	", ""],
["	heure de Jardinage","	281	", ""],
]

AppConversions.AddGroup(category.value, "Activité physique (personne de 70kg)", "", conversions);

var conversions = [
    ["	Bière “33” Export bouteille = 25 cl	","	97	", ""],
["	Bière canette = 33 cl	","	178	", ""],
["	Bière sans alcool canette = 33 cl	","	9	", ""],
["	Café pour 100 ml	","	15	", ""],
["	Calvados verre à liqueur = 4 cl	","	100	", ""],
["	Champagne brut flûte	","	70	", ""],
["	Champagne doux flûte	","	120	", ""],
["	Cidre brut bolée = 25 cl	","	77	", ""],
["	Coca cola verre = 250 ml	","	100	", ""],
["	Cognac verre = 4 cl	","	192	", ""],
["	Eau pour 100 ml	","	0	", ""],
["	Eau-de-vie verre à liqueur = 4 cl	","	100	", ""],
["	Martini verre = 8 cl	","	128	", ""],
["	Mojito	","	100	", ""],
["	Mousseux coupe = 10 cl	","	70	", ""],
["	Muscat verre = 15 cl	","	240	", ""],
["	Oasis orange verre = 15 cl	","	68	", ""],
["	Orangina light verre = 15 cl	","	11	", ""],
["	Orangina verre = 15 cl	","	71	", ""],
["	Pastis dose = 4 cl	","	130	", ""],
["	Pepsi pour 100ml	","	42	", ""],
["	Perrier	","	0	", ""],
["	Porto verre = 7 cl	","	80	", ""],
["	Punch verre = 8 cl	","	150	", ""],
["	Rhum verre = 4 cl	","	154	", ""],
["	Ricard dose = 4 cl	","	130	", ""],
["	Sirop à l’eau 10 g pour 1 verre	","	33	", ""],
["	Spiritueux verre = 4 cl	","	112	", ""],
["	Sprite 1 verre = 15 cl	","	54	", ""],
["	Suze verre = 8 cl	","	84	", ""],
["	Thé glacé pour 100ml	","	30	", ""],
["	Thé pour 100 ml	","	0	", ""],
["	Vermouth verre = 7 cl	","	77	", ""],
["	Vin blanc 10° verre = 15 cl	","	108	", ""],
["	Vin cuit verre = 7 cl	","	160	", ""],
["	Vin rouge 12° verre = 15 cl	","	105	", ""],
["	Vodka	","	217	", ""],
["	Vodka verre à liqueur = 4 cl	","	100	", ""],
["	Whisky verre = 8 cl	","	384	", ""],

]

AppConversions.AddGroup(category.value, "Alcools & Spiritueux" , "",conversions);

var conversions = [
    ["	Agneau (cervelle)	 100g	","	112	", ""],
["	Agneau (côtelettes)	 100g	","	330	", ""],
["	Agneau (épaule)	 100g	","	289	", ""],
["	Agneau (foie)	 100g	","	132	", ""],
["	Agneau (gigot)	 100g	","	250	", ""],
["	Agneau (langue)	 100g	","	193	", ""],
["	Agneau (rognon)	 100g	","	87	", ""],
["	Agneau (selle)	 100g	","	234	", ""],
["	Andouille et andouillette	 100g	","	300	", ""],
["	Bacon	 100g	","	385	", ""],
["	Bécasse	 100g	","	115	", ""],
["	Boeuf (aloyau)	 100g	","	266	", ""],
["	Boeuf (araignée)	 100g	","	200	", ""],
["	Boeuf (bavette)	 100g	","	200	", ""],
["	Boeuf (Bifteck)	 100g	","	200	", ""],
["	Boeuf (cervelle, coeur)	 100g	","	130	", ""],
["	Boeuf (corned-beef)	 100g	","	275	", ""],
["	Boeuf (côte)	 100g	","	260	", ""],
["	Boeuf (culotte)	 100g	","	289	", ""],
["	Boeuf (entrecôte)	 100g	","	200	", ""],
["	Boeuf (faux-filet)	 100g	","	156	", ""],
["	Boeuf (filet)	 100g	","	180	", ""],
["	Boeuf (gîte)	 100g	","	300	", ""],
["	Boeuf (hampe)	 100g	","	200	", ""],
["	Boeuf (langue)	 100g	","	200	", ""],
["	Boeuf (macreuse)	 100g	","	242	", ""],
["	Boeuf (noix)	 100g	","	184	", ""],
["	Boeuf (onglet)	 100g	","	200	", ""],
["	Boeuf (paleron)	 100g	","	216	", ""],
["	Boeuf (plates côtes)	 100g	","	250	", ""],
["	Boeuf (rosbif)	 100g	","	160	", ""],
["	Boeuf (rumsteack)	 100g	","	200	", ""],
["	Boeuf (tournedos)	 100g	","	200	", ""],
["	Boeuf (tripes)	 100g	","	94	", ""],
["	Bœuf (steak haché)	 100g	","	239	", ""],
["	Caille	 100g	","	115	", ""],
["	Canard	 100g	","	250	", ""],
["	Canard sauvage	 100g	","	126	", ""],
["	Cerf	 100g	","	116	", ""],
["	Cervelle	 100g	","	125	", ""],
["	Cheval (steack)	 100g	","	110	", ""],
["	Chevreau	 100g	","	160	", ""],
["	Chevreuil	 100g	","	120	", ""],
["	Corned-beef	 100g	","	275	", ""],
["	Dinde, viande rôtie	 100g	","	160	", ""],
["	Dindonneau	 100g	","	260	", ""],
["	Faisan	 100g	","	106	", ""],
["	Grenouille (cuisses)	 100g	","	72	", ""],
["	Grive	 100g	","	120	", ""],
["	Hamburger	 100g	","	560	", ""],
["	Hot-dog (unité)	 100g	","	400	", ""],
["	Jambon blanc cuit à l’eau	 100g	","	50	", ""],
["	Jambon cru	 100g	","	330	", ""],
["	Jambon cuit, Jambonneau	 100g	","	290	", ""],
["	Jambon fumé	 100g	","	385	", ""],
["	Langue	 100g	","	200	", ""],
["	Lapin de garenne	 100g	","	133	", ""],
["	Lard	 100g	","	575	", ""],
["	Lard fumé	 100g	","	670	", ""],
["	Lièvre	 100g	","	100	", ""],
["	Merguez	 100g	","	520	", ""],
["	Moelle	 100g	","	605	", ""],
["	Mouton (cervelle, foie)	 100g	","	130	", ""],
["	Mouton (côtes, épaule)	 100g	","	300	", ""],
["	Mouton (gigot, selle)	 100g	","	250	", ""],
["	Œuf dur	 100g	","	70	", ""],
["	Œuf au plat	 100g	","	90	", ""],
["	Œuf poché	 100g	","	143	", ""],
["	Oie	 100g	","	350	", ""],
["	Perdreau	 100g	","	115	", ""],
["	Perdrix	 100g	","	115	", ""],
["	Petit salé	 100g	","	330	", ""],
["	Pigeon	 100g	","	108	", ""],
["	Pintade	 100g	","	108	", ""],
["	Porc (filet, côtes, palette...)	 100g	","	300	", ""],
["	Poulet	 100g	","	150	", ""],
["	Sanglier	 100g	","	104	", ""],
["	Tartare (steack)	 100g	","	200	", ""],
["	Travers de porc	 100g	","	305	", ""],
["	Tripes	 100g	","	94	", ""],
["	Veau (épaule, noix, quasi...)	 100g	","	168	", ""],
["	Foie de veau	 100g	","	137	", ""],
 ["	Ris de veau	 100g	","	116	", ""],
["	Rognon de veau	 100g	","	123	", ""],
["	Tête de veau	 100g	","	210	", ""],

]

AppConversions.AddGroup(category.value, "Viandes", "", conversions);


var conversions = [
    ["	Cervelas	 100g	","	320	", ""],
    ["	Chair à saucisse	 100g	","	422	", ""],
    ["	Charcuterie	 100g	","	450	", ""],
    ["	Foie gras	 100g	","	450	", ""],
["	Fromage de tête	 100g	","	342	", ""],
["	Mortadelle	 100g	","	305	", ""],
["	Mousse de foie	 100g	","	410	", ""],
["	Museau de porc	 100g	","	342	", ""],
["	Pâté de campagne	 100g	","	455	", ""],
["	Pâté de foie	 100g	","	465	", ""],
["	Pâté de tête	 100g	","	342	", ""],
["	Rillettes	 100g	","	250	", ""],
["	Rillettes d’oie	 100g	","	464	", ""],
["	Salami	 100g	","	410	", ""],
["	Ssaucisse pur porc	 100g	","	330	", ""],
["	Saucisson pur porc	 100g	","	440	", ""],

]

AppConversions.AddGroup(category.value, "Charcuterie", "", conversions);

var conversions = [
    ["	Aiglefin	","	71	", ""],
["	Anchois	","	160	", ""],
["	Anguille	","	230	", ""],
["	Anguille fumée	","	305	", ""],
["	Araignée de mer	","	95	", ""],
["	Bar	","	90	", ""],
["	Barbue	","	117	", ""],
["	Baudroie ou lotte	","	79	", ""],
["	Bigorneaux (décortiqués)	","	100	", ""],
["	Brème	","	100	", ""],
["	Brochet	","	78	", ""],
["	Cabillaud ou morue	","	79	", ""],
["	Calmar	","	89	", ""],
["	Carpe d’élevage	","	90	", ""],
["	Carpe sauvage	","	145	", ""],
["	Carrelet	","	65	", ""],
["	Caviar	","	275	", ""],
["	Clams	","	80	", ""],
["	Clovisses	","	50	", ""],
["	Colin ou merlu	","	92	", ""],
["	Congre	","	110	", ""],
["	Coques	","	47	", ""],
["	Coquille St-Jacques	","	74	", ""],
["	Couteaux	","	55	", ""],
["	Crabe frais	","	85	", ""],
["	Crevettes grises	","	98	", ""],
["	Daurade	","	77	", ""],
["	Ecrevisses	","	71	", ""],
["	Eglefin	","	71	", ""],
["	Encornet	","	89	", ""],
["	Eperlan	","	78	", ""],
["	Espadon	","	116	", ""],
["	Esturgeon	","	125	", ""],
["	Flétan	","	117	", ""],
["	Gambas	","	98	", ""],
["	Gardon	","	112	", ""],
["	Goujon	","	62	", ""],
["	Grondin	","	95	", ""],
["	Haddock	","	103	", ""],
["	Hareng frais	","	149	", ""],
["	Hareng fumé	","	200	", ""],
["	Homard	","	80	", ""],
["	Huîtres	","	70	", ""],
["	Lamproie	","	177	", ""],
["	Langouste	","	110	", ""],
["	Langoustine	","	90	", ""],
["	Lieu	","	90	", ""],
["	Limande	","	78	", ""],
["	Lotte ou baudroie	","	79	", ""],
["	Maquereau frais	","	128	", ""],
["	Merlan	","	90	", ""],
["	Mérou	","	225	", ""],
["	Mollusques	","	90	", ""],
["	Morue	","	79	", ""],
["	Morue salée	","	163	", ""],
["	Morue séchée	","	322	", ""],
["	Moules	","	70	", ""],
["	Mulet	","	151	", ""],
["	Murène	","	176	", ""],
["	Oeufs de lump	","	80	", ""],
["	Oeufs de poissons	","	225	", ""],
["	Omble ou ombre	","	123	", ""],
["	Ormeaux	","	92	", ""],
["	Oursins	","	70	", ""],
["	Pagre	","	77	", ""],
["	Palourdes	","	95	", ""],
["	Perche	","	112	", ""],
["	Pétoncles	","	50	", ""],
["	Pieuvre	","	61	", ""],
["	Plie	","	65	", ""],
["	Poissons à l’huile	","	325	", ""],
["	Poissons fumés	","	265	", ""],
["	Poissons gras	","	180	", ""],
["	Poissons maigres	","	75	", ""],
["	Poissons panés	","	175	", ""],
["	Poissons séchés	","	320	", ""],
["	Poulpe	","	70	", ""],
["	Praires	","	61	", ""],
["	Raie	","	89	", ""],
["	Rascasse	","	98	", ""],
["	Requin	","	106	", ""],
["	Rillettes de saumon	","	320	", ""],
["	Rollmops	","	224	", ""],
["	Rouget-barbet	","	148	", ""],
["	Rouget-grondin	","	95	", ""],
["	Roussette	","	106	", ""],
["	Saint-Pierre	","	74	", ""],
["	Sandre	","	112	", ""],
["	Sardine	","	162	", ""],
["	Sardines à l’huile	","	125	", ""],
["	Sardines fraîches	","	77	", ""],
["	Saumon frais	","	200	", ""],
["	Saumon fumé	","	265	", ""],
["	Saumonette	","	106	", ""],
["	Scampi	","	47	", ""],
["	Seiche	","	90	", ""],
["	Silure	","	250	", ""],
["	Sole	","	75	", ""],
["	Thon à l’huile	","	280	", ""],
["	Thon frais	","	225	", ""],
["	Tourteau	","	85	", ""],
["	Truite	","	103	", ""],
["	Truite saumonée	","	151	", ""],
["	Turbot	","	118	", ""],

]

AppConversions.AddGroup(category.value, "Poissons et crustacés" , "",conversions);


var conversions = [
    ["	Flageolets	","	84	", ""],
["	Haricots rouges	","	100	", ""],
["	Haricots blancs	","	100	", ""],
["	Lentilles vertes	","	100	", ""],
["	Maïs	","	54	", ""],
["	Pois cassés	","	122	", ""],
["	Pois chiches	","	160	", ""],
["	Artichaut	","	47	", ""],
["	Avocat	","	160	", ""],
["	Aubergine	","	24	", ""],
["	Brocolis	","	35	", ""],
["	Carotte	","	36	", ""],
["	Céleri	","	18	", ""],
["	Champignon	","	22	", ""],
["	Chou	","	18	", ""],
["	Chou-fleur	","	25	", ""],
["	Concombre	","	15	", ""],
["	Courgette	","	20	", ""],
["	Epinards	","	23	", ""],
["	Haricots verts	","	25	", ""],
["	Laitue	","	15	", ""],
["	Oignon	","	40	", ""],
["	Pois	","	80	", ""],
["	Poireau	","	31	", ""],
["	Poivron	","	21	", ""],
["	Radis	","	16	", ""],
["	Pâtes cuites	","	150	", ""],
["	Riz cuit	","	150	", ""],
["	Pain blanc	","	270	", ""],
["	Pain complet au levain	","	234	", ""],
["	Pomme de terre cuite	","	90	", ""],
["	Patate douce cuite	","	60	", ""],
["	Avoine cuit à l'eau	","	76	", ""],

]

AppConversions.AddGroup(category.value, "Légumes et féculents" , "",conversions);

var conversions = [
    ["	Noix de cajou	","	612	", ""],
["	Amandes	","	639	", ""],
["	Noisettes	","	680	", ""],
["	Noix	","	709	", ""],
["	Pistaches	","	608	", ""],
["	Sésame	","	599	", ""],

]

AppConversions.AddGroup(category.value, "Noix et fruits secs" , "",conversions);

var conversions = [
    ["	Brioche	","	386	", ""],
["	Brownie	","	400	", ""],
["	Chouquette	","	400	", ""],
["	Cookie au chocolat	","	500	", ""],
["	Confiture	","	250	", ""],
["	Croissant	","	400	", ""],
["	Pain au chocolat	","	435	", ""],
["	Pâte à tartiner au chocolat	","	550	", ""],
["	Quatre quart	","	430	", ""],

]

AppConversions.AddGroup(category.value, "Boulangerie" , "",conversions);

var conversions = [
    ["	Beurre	","	750	", ""],
["	Huile d’arachides	","	900	", ""],
["	Huile de colza	","	900	", ""],
["	Huile de paraffine	","	0	", ""],
["	Huile d’olives	","	900	", ""],
["	Saindoux	","	850	", ""],
["	Huile de soja	","	900	", ""],
["	Huile de tournesol	","	900	", ""],
["	Végétaline	","	900	", ""],
["	Graisse d’oie (1 cuil. soupe)	","	180	", ""],
["	Margarine	","	755	", ""],
["	Margarine (1 noisette)	","	75	", ""],
["	Margarine (1 noix)	","	75	", ""],

]

AppConversions.AddGroup(category.value, "graisses" , "",conversions);

var conversions = [
    ["	Crème fraîche	","	290	", ""],
["	Emmental	","	380	", ""],
["	Fromage blanc 0%	","	67	", ""],
["	Fromage de chèvre	","	200	", ""],
["	Lait	","	47	", ""],
["	Mozzarella	","	330	", ""],
["	Oeufs	","	145	", ""],
["	Yaourt nature 0%	","	62	", ""],
["	Yaourt nature au lait entier	","	100	", ""],
["	Beaufort	","	396	", ""],
["	Beurre allégé	","	410	", ""],
["	Bleus	","	410	", ""],
["	Bonbel	","	353	", ""],
["	Boursault	","	354	", ""],
["	Boursin	","	414	", ""],
["	Brie	","	263	", ""],
["	Camembert	","	312	", ""],
["	Cantal	","	386	", ""],
["	Carré de l’Est	","	362	", ""],
["	Chavignols	","	330	", ""],
["	Cheddar	","	382	", ""],
["	Chèvre	","	330	", ""],
["	Comté	","	396	", ""],
["	Coulommiers	","	278	", ""],
["	Crème de gruyère	","	280	", ""],
["	Crème fraîche	","	300	", ""],
["	Crème fraîche (1 c. à soupe)	","	60	", ""],
["	Crottins (fromage)	","	80	", ""],
["	Demisel	","	174	", ""],
["	Edam	","	353	", ""],
["	Emmenthal	","	415	", ""],
["	Fromage blanc à 0% aux fruits	","	80	", ""],
["	Fromage blanc à 0% MG	","	44	", ""],
["	Fromage blanc à 20% MG	","	80	", ""],
["	Fromage blanc à 40% MG	","	116	", ""],
["	Gorgonzola	","	405	", ""],
["	Gouda	","	353	", ""],
["	Gruyère	","	392	", ""],
["	Hollande	","	353	", ""],
["	Kéfir	","	44	", ""],
["	Lait 1/2 écrémé	","	49	", ""],
["	Lait concentré	","	130	", ""],
["	Lait concentré sucré	","	330	", ""],
["	Lait écrémé	","	34	", ""],
["	Lait écrémé (poudre)	","	375	", ""],
["	Lait entier	","	65	", ""],
["	Lait entier (poudre)	","	482	", ""],
["	Margarine	","	755	", ""],
["	Maroilles	","	420	", ""],
["	Mimolette	","	344	", ""],
["	Morbier	","	300	", ""],
["	Mozzarelle	","	332	", ""],
["	Munster	","	320	", ""],
["	Parmesan	","	393	", ""],
["	Pavé d’Auge	","	300	", ""],
["	Petitsuisse (40 %)	","	146	", ""],
["	Petitsuisse (60 %)	","	236	", ""],
["	PontLévêque	","	300	", ""],
["	Portsalut	","	362	", ""],
["	Pyrénées	","	365	", ""],
["	Reblochon	","	354	", ""],
["	Roquefort	","	405	", ""],
["	Rouy	","	362	", ""],
["	SaintFlorentin	","	312	", ""],
["	SaintMarcellin	","	228	", ""],
["	SaintNectaire	","	354	", ""],
["	SaintPaulin	","	365	", ""],
["	Tartare (portion 20 g)	","	69	", ""],
["	Tomme	","	354	", ""],
["	Yaourt à 0% (unité)	","	44	", ""],
["	Yaourt à 0% sucré	","	80	", ""],
["	Yaourt aromatisé	","	120	", ""],
["	Yaourt au chocolat	","	140	", ""],
["	Yaourt aux fruits	","	100	", ""],
["	Yaourt nature (unité)	","	55	", ""],
["	Apéricube (à l’unité)	","	16	", ""],

]

AppConversions.AddGroup(category.value, "Produits laitiers" , "",conversions);

var conversions = [
    ["	Abricot	","	43	", ""],
["	Ananas	","	55	", ""],
["	Banane	","	88	", ""],
["	Cerise	","	50	", ""],
["	Framboise	","	36	", ""],
["	Kiwi	","	51	", ""],
["	Mangue	","	62	", ""],
["	Mûre	","	43	", ""],
["	Pamplemousse	","	60	", ""],
["	Pomme	","	52	", ""],

]

AppConversions.AddGroup(category.value, "Fruits" , "",conversions);

var conversions = [
    ["	Bretzel (à l’unité 15 g)	","	80	", ""],
["	Chipster salé	","	460	", ""],
["	Chips Vico à l’ancienne saveur moutarde	","	549	", ""],
["	Crackers Belin Monaco emmental	","	555	", ""],
["	Monaco	","	507	", ""],
["	Olives noires	","	336	", ""],
["	Olives vertes	","	123	", ""],
["	Pringles original	","	540	", ""],

]

AppConversions.AddGroup(category.value, "Biscuits Apéritifs" , "",conversions);

